### ISSUE TITLE
[Feature Request] Ability to sort groups

### ISSUE THREAD

**Issue by Ryan-B-W** [julianpoy/OpenRetro#15]
Some way of sorting groups would be nice.  Currently, groups are auto sorted by, what appears to be, time of submission of each card.

**Comment by julianpoy** [comment]
I made it such that you can re-order cards within groups and now realize the ask might have been more targeted towards re-ordering groups themselves.

**Comment by Ryan-B-W** [comment]
The desire was to reorder items within a group.  While it would be nice to have moving groups between columns, I'll consider b022a11 sufficient to close this particular item.
